version: "3"

networks:
  loki:

services:
  loki-test-app:
    container_name: loki-test-app
    image: loki-test-app:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - loki
    labels:
      - "logging=promtail"

  loki:
    image: grafana/loki:2.9.2
    volumes:
      - /home/haspe/dev/loki-test-app/volumes/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/haspe/dev/loki-test-app/volumes/promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
      - /home/haspe/dev/loki-test-app/volumes/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki
